name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install coverage pytest
      - name: Run tests with coverage
        run: coverage run -m pytest
      - name: Generate coverage report
        run: coverage xml
      - name: Python Coverage Comment
        uses: py-cov-action/python-coverage-comment-action@v3.38
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: coverage.xml
