name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install pytest coverage
      - name: Run tests with coverage
        run: coverage run --source=image_cli,sora_cli -m pytest
      - name: Publish coverage summary
        run: |
          coverage report --show-missing > coverage.txt
          cat coverage.txt
          {
            echo '### Coverage Summary';
            echo '```';
            cat coverage.txt;
            echo '```';
          } >> "$GITHUB_STEP_SUMMARY"
